server:
  port: 8000

spring:
  application:
    name: users
  jackson:
    property-naming-strategy: SNAKE_CASE

#    Para utilização com MongoDB, descomente as duas linhas abaixo, além das dependências no pom.xml.
#  data:
#    mongodb.uri: mongodb://${DB_URL:localhost}/users

#    Para utilização com MySQL, descomente as duas linhas abaixo, além das dependências no pom.xml.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:root@${DB_URL:localhost}/users?useSsl=false

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update #create
      dialect: org.hibernate.dialect.MySQL57Dialect